export const SEARCH = "SEARCH";
export const CLICK = "CLICK";
export const CHANGE_LANGUAGE_TO_ARABIC = "CHANGE_LANGUAGE_TO_ARABIC";
export const CHANGE_LANGUAGE_TO_ENGLISH = "CHANGE_LANGUAGE_TO_ENGLISH";